#! python scons

Import('env')

env_solarpilot = env.Clone()

env_solarpilot.AppendUnique(
	CPPPATH=['#','../nlopt','../lpsolve']
)

srcs = Split("""fluxsim.cpp API_structures.cpp Ambient.cpp AutoPilot_API.cpp
	Financial.cpp Flux.cpp Heliostat.cpp IOUtil.cpp Land.cpp 
	LayoutSimulateThread.cpp OpticalMesh.cpp Receiver.cpp STObject.cpp 
	STSimulateThread.cpp SolarField.cpp Toolbox.cpp definitions.cpp heliodata.cpp
	interop.cpp mod_base.cpp optimize.cpp solpos.cpp string_util.cpp""")

objs = []
for s in srcs:
	objs.append(env_solarpilot.SharedObject(s))
#lib = env_solarpilot.Library("solarpilot",srcs)

Return('objs')
