#! python scons

Import('env')

srcs = Split("""auglag.c
	bobyqa.c
	ccsa_quadratic.c
	cdirect.c
	cobyla.c
	crs.c
	deprecated.c
	DIRect.c
	direct_wrap.c
	DIRserial.c
	DIRsubrout.c
	esch.c
	general.c
	hybrid.c
	isres.c
	mlsl.c
	mma.c
	mssubs.c
	mt19937ar.c
	newuoa.c
	nldrmd.c
	optimize.c
	options.c
	plip.c
	plis.c
	pnet.c
	praxis.c
	pssubs.c
	qsort_r.c
	redblack.c
	rescale.c
	sbplx.c
	slsqp.c
	sobolseq.c
	stop.c
	timer.c""")

env.AppendUnique(CPPDEFINES=['-DTHREADLOCAL=__thread'])

objs = []
for s in srcs:
	objs.append(env.SharedObject(s))

#lib = env.Library("nlopt.a",srcs)

Return('objs')

